### ISSUE TITLE
Broadcast does not work

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/real-time-game-quiz-4ahif-SimonPrimetzhofer#1]
Dear Mr. Stropek!

I've got a function called scoreEvaluation() in server.ts line 65-120...

I'm trying to do a broadcast to all clients with sio(server).emit("win",DODGER) for example.
But the broadcast doesn't get through to the client and I have no idea why.

Normal messages over the sockets work fine, but the broadcast does not.

Could you please have a look at it?

Greetings,
Simon Primetzhofer

**Comment by rstropek** [comment]
Hi @SimonPrimetzhofer 

Unfortunately, I cannot currently try your code. However, I took a look at the code and I have an educated guess. Your code contains many calls like this: `sio(server)`. In the [socket.io docs](https://socket.io/docs/server-api/) you see that this creates a **new** socket.io server every time.

So my tips is that you call `sio(server)` only once and store the result in a variable. Use this variable wherever you currently use `sio(server)`. Can you try that and give me feedback whether it helps?

Greetings,
Rainer Stropek.

**Comment by SimonPrimetzhofer** [comment]
Dear Mr. Stropek!

That was the mistake I made. Thanks for your help.

Greetings,
Simon Primetzhofer
